name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: package
        path: |
          .
          !.git
          !.github
          !.gitignore
          !scripts
          !*.md
          !.Dockerfile

  build_container:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
